name: Maven Build and Test

on:
  push:
    branches: ['*']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK 19
      uses: actions/setup-java@v1
      with:
        java-version: '19'

    - name: Compile
      run: mvn compile


  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK 19
      uses: actions/setup-java@v1
      with:
        java-version: '19'

    - name: Run unit tests
      run: mvn -B test
